Repository redneckz/wildless-cms-uni-blocks, pull requests merged in 2022-08, with the labels that each got.

#162 Adjust *Content types and fix JSON Schema definitions
  .eslintrc.cjs
  docs/main.js.map
  jest.config.cjs
  scripts/__snapshots__/build-schema.spec.ts.snap
  scripts/build-schema.js
  scripts/build-schema.spec.ts
  src/components/BaseTile/BaseTileProps.ts
  src/components/Headline/HeadlineContent.ts
  src/components/MobileAppTile/MobileAppTileContent.ts
  src/components/ProductBlock/ProductBlockContent.ts
  src/components/ProductBlock/ProductBlockInner.tsx
  src/components/ProductTile/ProductTileContent.ts
  src/components/Tile/TileContent.ts
  src/ui-kit/Heading/HeadingProps.ts
Labels: enhancement

#161 footer content fix
  docs/icons/DischountStarIcon.svg
  docs/icons/DocumentText.svg
  docs/main.js
  docs/main.js.map
  docs/mobile/icons/DischountStarIcon.svg
  docs/mobile/icons/DocumentText.svg
  docs/mobile/main.js.map
  src/components/ContentPage/ContentPage.page.json
  src/components/Footer/Footer.fixture.tsx
Labels: bug

#159 fix and refactor
  docs/main.js
  docs/main.js.map
  docs/mobile/main.js
  docs/mobile/main.js.map
  src/components/BaseTile/renderButton.tsx
  src/components/Headline/Headline.fixture.tsx
  src/components/TariffsTable/TariffsTableCell.tsx
  src/ui-kit/Button/Button.fixture.tsx
Labels: bug

#163 Bugfix/tile fix
  docs/main.js
  docs/main.js.map
  docs/mobile/main.js
  docs/mobile/main.js.map
  src/components/BaseTile/BaseTile.tsx
  src/components/Header/Header.fixture.mobile.tsx
  src/components/PromoTile/PromoTile.fixture.tsx
  src/components/TariffsTable/TariffsTable.fixture.tsx
  src/components/Tile/Tile.fixture.tsx
  src/ui-kit/BlockItem/BlockItem.tsx
  src/ui-kit/Heading/Heading.fixture.mobile.tsx
  src/ui-kit/Heading/Heading.fixture.tsx
Labels: bug

#151 Feature/accordion extension
  docs/main.js
  docs/main.js.map
  docs/mobile/main.js
  docs/mobile/main.js.map
  scripts/__snapshots__/build-schema.spec.ts.snap
  src/components/Accordion/Accordion.fixture.mobile.tsx
  src/components/Accordion/Accordion.fixture.tsx
  src/components/Accordion/AccordionBlocks.tsx
  src/components/Accordion/AccordionContent.ts
  src/components/BaseTile/BaseTileInner.tsx
  src/components/Gallery/Gallery.fixture.tsx
  src/components/MiniGallery/MiniGallery.fixture.tsx
  src/components/ProductTile/ProductTile.fixture.tsx
  src/components/Tile/Tile.fixture.tsx
Labels: enhancement

#142 feature gallery mobile
  docs/main.js
  docs/main.js.map
  docs/mobile/main.js
  docs/mobile/main.js.map
  scripts/__snapshots__/build-schema.spec.ts.snap
  src/components/Gallery/Gallery.fixture.mobile.tsx
  src/components/Gallery/Gallery.fixture.tsx
  src/components/Gallery/Gallery.mobile.tsx
  src/components/Gallery/GalleryCardInner.tsx
  src/components/Gallery/GalleryContent.ts
  src/model/ButtonVersion.ts
  src/ui-kit/Button/Button.mobile.tsx
  src/ui-kit/Button/Button.tsx
  src/ui-kit/Button/ButtonInner.tsx
Labels: enhancement

#194 fix issues 96 and 117 / refactor
  src/components/BaseTile/BaseTile.tsx
  src/components/ComparisonTable/ComparisonTable.fixture.tsx
  src/components/ExchangeRateTile/ExchangeRateTile.tsx
  src/components/Gallery/Gallery.fixture.mobile.tsx
  src/components/Gallery/GalleryCardInner.tsx
  src/components/ProductBlock/ProductBlock.fixture.mobile.tsx
  src/components/ProductBlock/ProductBlockInner.mobile.tsx
  src/components/ProductBlock/ProductBlockInner.tsx
  src/components/ProductGallery/ProductGallery.fixture.mobile.tsx
  src/components/ProductGallery/ProductGallery.fixture.tsx
  src/components/ProductGallery/ProductGallery.mobile.tsx
  src/components/ProductGallery/ProductGalleryBlock.mobile.tsx
  src/components/StepsBlock/StepsBlock.mobile.tsx
  src/components/Tile/Tile.tsx
  src/ui-kit/BlockItem/BlockItem.tsx
  src/ui-kit/Description/Description.tsx
  src/ui-kit/Heading/Heading.fixture.mobile.tsx
  src/ui-kit/List/ListItem.tsx
  src/ui-kit/SwipeListControl/SwipeListControlDots.tsx
Labels: bug

#202 update blocks.ts and blocks.mobile.ts
  src/components/Blocks.mobile.ts
  src/components/Blocks.ts
Labels: bug

#208 footer fix issues-91
  src/components/Footer/Contacts.tsx
  src/components/Footer/Footer.mobile.tsx
  src/components/Footer/HorizontalNavigation.mobile.tsx
  src/components/Footer/TextInformation.mobile.tsx
  src/components/MobileAppTile/MobileAppTile.mobile.tsx
Labels: bug

#213 fix button width
  src/components/Gallery/GalleryCardInner.tsx
  src/ui-kit/BlockItem/BlockItem.tsx
Labels: bug

#215 add icon in button componen
  src/components/Gallery/Gallery.fixture.mobile.tsx
  src/components/Gallery/Gallery.fixture.tsx
  src/components/Gallery/Gallery.mobile.tsx
  src/components/Gallery/GalleryCardInner.tsx
  src/components/ProductBlock/ProductBlockInner.mobile.tsx
  src/components/ProductGallery/ProductGallery.fixture.mobile.tsx
Labels: bug

#216 fix gallery issues 129
  src/components/Gallery/Gallery.example.json
  src/components/ProductBlock/ProductBlockInner.tsx
Labels: bug

#221 Bump version to 0.3.10
  .public.package.json
Labels: enhancement

#224 fix ProductBlock component and refactor (issues 96)
  src/components/ProductBlock/ProductBlock.example.json
  src/components/ProductBlock/ProductBlock.fixture.mobile.tsx
  src/components/ProductBlock/ProductBlock.fixture.tsx
  src/components/ProductBlock/ProductBlockInner.mobile.tsx
  src/components/ProductBlock/ProductBlockInner.tsx
Labels: bug

#225 add filter for benefits object emptiness
  .public.package.json
  src/components/ProductBlock/ProductBlockInner.mobile.tsx
  src/components/ProductBlock/ProductBlockInner.tsx
Labels: bug

#233 fix accordion mobile styles
  src/components/Accordion/AccordionItem.mobile.tsx
  src/components/Accordion/AccordionItemInner.mobile.tsx
Labels: bug

#234 Refactor Button and document some conventions
  .eslintrc.cjs
  DEVDOC.md
  package-lock.json
  src/ui-kit/Button/Button.tsx
  src/ui-kit/Button/ButtonInner.tsx
Labels: enhancement

#245 update annotations for scrolled mobile component
  cypress/snapshots/base/blocksVisualRegressionDesktop.cy.ts/CreditCalculator_default-base.png
  cypress/snapshots/base/blocksVisualRegressionDesktop.cy.ts/PromoTile_default-base.png
  cypress/snapshots/base/blocksVisualRegressionMobile.cy.ts/Gallery_default-base.png
  cypress/snapshots/base/blocksVisualRegressionMobile.cy.ts/Gallery_scroll-base.png
  scripts/__snapshots__/build-schema.spec.ts.snap
  src/components/ComparisonTable/TableColumn.tsx
  src/components/Gallery/Gallery.fixture.mobile.tsx
  src/components/Gallery/Gallery.mobile.tsx
  src/components/Gallery/GalleryContent.ts
  src/components/Header/HeaderContent.ts
  src/components/MobileAppTile/MobileAppTile.tsx
  src/components/ProductBlock/ProductBlock.fixture.tsx
  src/components/ProductBlock/ProductBlockContent.ts
  src/components/ProductGallery/ProductGalleryContent.ts
  src/components/TariffsTable/TariffsTable.mobile.tsx
  src/components/TariffsTable/TariffsTableTileCell.tsx
Labels: bug

#240 add two column options in accordion component and refactor feature
  cypress/snapshots/base/blocksVisualRegressionDesktop.cy.ts/Accordion_default-base.png
  cypress/snapshots/base/blocksVisualRegressionDesktop.cy.ts/Accordion_two columns-base.png
  cypress/snapshots/base/blocksVisualRegressionDesktop.cy.ts/ProductBlock_with items-base.png
  cypress/snapshots/base/blocksVisualRegressionDesktop.cy.ts/ProductBlock_without image-base.png
  cypress/snapshots/base/blocksVisualRegressionDesktop.cy.ts/ProductTile_credit-card-base.png
  cypress/snapshots/base/blocksVisualRegressionDesktop.cy.ts/ProductTile_pension-base.png
  cypress/snapshots/base/blocksVisualRegressionDesktop.cy.ts/ProductTile_pension-credit-base.png
  scripts/__snapshots__/build-schema.spec.ts.snap
  src/components/Accordion/Accordion.fixture.tsx
  src/components/Accordion/AccordionBlocks.tsx
  src/components/Accordion/AccordionContent.ts
  src/components/Accordion/AccordionItem.tsx
  src/components/Accordion/AccordionItemInner.tsx
  src/components/ProductBlock/ProductBlock.fixture.tsx
  src/components/ProductTile/ProductTile.fixture.tsx
  src/components/Tile/Tile.fixture.tsx
Labels: enhancement

#247 textblock style fix
  cypress/snapshots/base/blocksVisualRegressionMobile.cy.ts/TextBlock_default-base.png
  src/components/TextBlock/TextBlock.fixture.mobile.tsx
  src/components/TextBlock/TextBlock.mobile.tsx
Labels: bug

#246 change tests structure
  .github/workflows/e2e-update-snapshots.yaml
  .github/workflows/e2e-visual-regression.yml
  .gitignore
  cypress.config.ts
  cypress/e2e/blocksVisualRegressionDesktop.cy.ts
  cypress/e2e/blocksVisualRegressionMobile.cy.ts
  cypress/fixtures/blockFixturesMap.json
  cypress/pages/blockFixture.ts
Labels: bug

#252 extended background-color props in headline components
  scripts/__snapshots__/build-schema.spec.ts.snap
  src/components/Headline/Headline.example.json
  src/components/Headline/Headline.fixture.mobile.tsx
  src/components/Headline/Headline.fixture.tsx
  src/components/Headline/Headline.mobile.tsx
  src/components/Headline/Headline.tsx
  src/components/Headline/HeadlineContent.ts
  src/components/Headline/constants.ts
  src/model/BlockVersion.ts
Labels: enhancement

#257 extended background-color props and style fix
  .public.package.json
  scripts/__snapshots__/build-schema.spec.ts.snap
  src/components/Headline/Headline.mobile.tsx
  src/components/Headline/Headline.tsx
  src/components/Headline/constants.ts
  src/components/StepsBlock/StepsBlock.fixture.mobile.tsx
  src/components/StepsBlock/StepsBlock.mobile.tsx
  src/components/StepsBlock/StepsBlockContent.ts
Labels: enhancement

#267 Document common definitions regarding uni blocks
  README.md
Labels: documentation

#274 small fix in Gallery / MiniGallery / Headline / MobileApp
  scripts/__snapshots__/build-schema.spec.ts.snap
  scripts/schema-sort-index.js
  src/components/ContentPage/ContentPage.page.json
  src/components/Gallery/Gallery.example.json
  src/components/Gallery/GalleryContent.ts
  src/components/Headline/Headline.tsx
  src/components/MiniGallery/MiniGalleryContent.ts
  src/components/MobileAppTile/MobileAppTile.mobile.tsx
  src/model/BlockVersion.ts
Labels: bug

#277 footer searchBar border fix
  src/ui-kit/SearchBar/SearchBar.mobile.tsx
Labels: bug

#282 style fix gallery and otherProducts
  src/components/Gallery/GalleryCardInner.tsx
  src/components/OtherProducts/OtherProductsItem.tsx
Labels: bug

#284 style fix and default minItems changed to 4 on miniGallery
  scripts/__snapshots__/build-schema.spec.ts.snap
  src/components/MiniGallery/MiniGalleryContent.ts
  src/components/OtherProducts/OtherProductsItem.tsx
Labels: bug

#269 Feature/block with tabs
  scripts/__snapshots__/build-schema.spec.ts.snap
  src/common.css
  src/components/Accordion/Accordion.tsx
  src/components/BaseTile/BaseTile.tsx
  src/components/BenefitsBlock/BenefitsBlock.tsx
  src/components/BlockContent.ts
  src/components/Blocks.ts
  src/components/ComparisonTable/ComparisonTable.tsx
  src/components/ContentPage/ContentPage.page.json
  src/components/ContentPage/ContentPage.tsx
  src/components/ContentPage/ContentPageContext.tsx
  src/components/CreditCalculator/CreditCalculator.tsx
  src/components/ExchangeRateTile/ExchangeRateTile.tsx
  src/components/Footer/Footer.tsx
  src/components/Gallery/GalleryInner.tsx
  src/components/Header/Header.tsx
  src/components/Headline/Headline.tsx
  src/components/LikeControl/LikeControl.tsx
  src/components/LinkDocs/LinkDocs.tsx
  src/components/LinkList/LinkList.tsx
  src/components/MobileAppTile/MobileAppTile.tsx
  src/components/Navigation/Navigation.tsx
  src/components/NavigatorTabs/NavigatorTabItem.tsx
  src/components/NavigatorTabs/NavigatorTabs.example.json
  src/components/NavigatorTabs/NavigatorTabs.fixture.tsx
  src/components/NavigatorTabs/NavigatorTabs.tsx
  src/components/NavigatorTabs/NavigatorTabsContent.ts
  src/components/PictureText/PictureText.tsx
  src/components/Placeholder/Placeholder.tsx
  src/components/ProductBlock/ProductBlock.tsx
  src/components/ProductGallery/ProductGallery.tsx
  src/components/ProductGalleryGreen/ProductGalleryGreen.tsx
  src/components/ProductTile/ProductTile.tsx
  src/components/PromoTile/PromoTile.tsx
  src/components/Recommendation/Recommendation.tsx
  src/components/StepsBlock/StepsBlock.tsx
  src/components/TariffsTable/TariffsTable.tsx
  src/components/TextBlock/TextBlock.tsx
  src/components/Tile/Tile.tsx
  src/services/sitemap/isTopItemActive.spec.ts
  src/setup-fixture.ts
  src/types.ts
  src/utils/url.ts
Labels: enhancement

#298 Правки по аккордеону issues #286
  scripts/__snapshots__/build-schema.spec.ts.snap
  scripts/schema-sort-index.js
  src/components/Accordion/Accordion.example.json
  src/components/Accordion/Accordion.fixture.mobile.tsx
  src/components/Accordion/Accordion.fixture.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/AccordionContent.ts
  src/components/Accordion/AccordionItem.mobile.tsx
  src/components/Accordion/AccordionItem.tsx
  src/components/Accordion/AccordionItemInner.mobile.tsx
  src/components/Accordion/AccordionItemInner.tsx
  src/components/Footer/MediaButton.tsx
  src/ui-kit/BlocksList/EmbeddableBlocks.mobile.tsx
  src/ui-kit/BlocksList/renderBlocksList.tsx
Labels: bug
